
- name: deploy dakara to all nodes
  hosts: all
  become: yes

  roles:
    - dakara
    - nginx

  vars:
    update_apt_cache: yes
    application_hostname: example.com
    clean_application_directory: no
    setup_from_git: no
