
- name: deploy dakara to all nodes
  hosts: all
  become: yes

  roles:
    - dakara
    - nginx

  vars:
    application_name: dakara
    update_apt_cache: yes
    application_hostname: example.com
