---

- name: Create the application user
  user: name={{ daphne_user }} state=present

- name: Create the application group
  group: name={{ daphne_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ daphne_user }} group={{ daphne_group }} state=present