---

- name: Install required packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=present
  with_items:
    - git
    - "{{ base_python_package }}-pip"
    - "i{{ base_python_package }}"
    - supervisor
    - unzip
  tags:
    - packages
