---

- name: Install required packages
  apt: 
    name: ['git', '{{ base_python_package }}-pip', 'i{{ base_python_package }}', 'supervisor', 'unzip']
    update_cache: '{{ update_apt_cache }}'
    state: present
  tags:
    - packages
