---

- name: Download and extract project archive
  unarchive:
    src: "{{ project_archive_url }}"
    dest: "{{ application_path }}"
    remote_src: yes
    creates: "{{ project_path }}_{{ project_archive_version }}/"
  notify: restart application

- name: Link project directory to the right place
  file:
    src: "{{ project_path }}_{{ project_archive_version }}/"
    dest: "{{ project_path }}"
    state: link

