---

- name: Install virtualenv
  pip:
    name: virtualenv
    version: 15.1.0
  tags: packages

- name: Check if Supervisor exists
  stat: path=/etc/init.d/supervisor
  register: supervisor_status
  when: clean_application_directory

- name: Ensure all processes managed by Supervisor are stopped if exists
  command: supervisorctl stop all
  when: clean_application_directory and supervisor_status.stat.exists

- name: Delete application directory
  file:
    state: absent
    path: "{{ application_path }}/"
  when: clean_application_directory

- name: Create the virtualenv
  command: virtualenv -p {{ virtualenv_python_version }} {{ virtualenv_path }}
           creates={{ virtualenv_path }}/bin/activate

- name: Ensure Daphne is installed in the virtualenv
  pip:
      virtualenv: '{{ virtualenv_path }}'
      name: ['daphne==2.2.5']

- name: Create the Daphne script file
  template: src=daphne_start.j2
            dest={{ virtualenv_path }}/bin/daphne_start
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0755
            backup=yes
  tags: deploy

- name: Create the application log folder
  file: path={{ application_log_dir }}
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0774
        state=directory

- name: Create (or retain) the application log file
  copy: content=""
        dest={{ application_log_file }}
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0664
        force=no

- name: Create the virtualenv postactivate script to set environment variables
  template: src=virtualenv_postactivate.j2
            dest={{ virtualenv_path }}/bin/postactivate
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0640
            backup=yes
  notify: restart application
  tags: deploy
