---

application_name: dakara
project_name: dakara-server
django_project_name: dakara_server
project_front_name: dakara-client-web

# Url to the dakara-server release
project_archive_version: "1.2.0"
project_archive_url: https://github.com/DakaraProject/dakara-server/releases/download/{{ project_archive_version }}/dakara-server_{{ project_archive_version }}.zip

# Alternatively, it's possible to build the project from the source repos
# It takes more time to set up, requires nodejs to build the front
# But this allows to install development versions
setup_from_git: no
git_repo: https://github.com/DakaraProject/dakara-server.git
git_front_repo: https://github.com/DakaraProject/dakara-client-web.git
git_version: master
git_front_version: master
nodejs_version: 9

# Virtualenv settings.
base_python_package: "{{ ansible_python_interpreter | default('/usr/bin/python') | basename }}"
virtualenv_python_version: "python3"


# Application settings.
application_path: "/webapps/{{ application_name }}"
virtualenv_path: "{{ application_path }}/virtualenv"
project_path: "{{ application_path }}/{{ project_name }}"
django_path: "{{ project_path }}/{{ django_project_name }}"
project_front_path: "{{ application_path }}/{{ project_front_name }}"
config_dir: "{{ application_path }}/config"
application_log_dir: "{{ application_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements.txt"
clean_application_directory: no


# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps
gunicorn_socket_file: "{{ application_path }}/run/gunicorn.sock"
gunicorn_max_requests: 0
gunicorn_num_workers: 1


# Nginx settings.
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ application_path }}/static/"

# Django settings
django_default_user_name: admin
django_default_user_password: admin
django_secret_key: "gjklhjksdghwhe;lfghaohfa;ohtpq3489fdgyt348tha;ihgtjk;asedgaiwu;egw;afgfg"
django_sqlite_file_path: "{{ application_path }}/db.sqlite3"
django_log_file: "{{ application_log_dir }}/django.log"
