---
project_name: dakara-server
django_project_name: dakara_server
project_front_name: dakara-client-web

git_repo: https://github.com/DakaraProject/dakara-server.git
git_branch: master

# Virtualenv settings.
recreate_virtualenv: no
base_python_package: "python3"
virtualenv_python_version: "python3"


# Application settings.
virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
django_path: "{{ project_path }}/{{ django_project_name }}"
project_front_path: "{{ virtualenv_path }}/{{ project_front_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements.txt"


# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps
gunicorn_socket_file: "{{ virtualenv_path }}/run/gunicorn.sock"
gunicorn_max_requests: 0
gunicorn_num_workers: 3


# Nginx settings.
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ virtualenv_path }}/static/"

django_secret_key: "gjklhjksdghwhe;lfghaohfa;ohtpq3489fdgyt348tha;ihgtjk;asedgaiwu;egw;afgfg"
sqlite_file_location: "{{ virtualenv_path }}"
